AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create S3 Bucket for Lambda functions.

Parameters:
  StackName:
    Type: String
    Description: Stack name.
    Default: prod

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${StackName}-lambda-code-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
